### ISSUE TITLE
Visual reference to example? 

### ISSUE THREAD

**Issue by Averysaurus** [dlab-berkeley/R-Data-Visualization#19]
on line 59, we reference a "Chloropleth Map". Students may not know what that is on their own. Is it possible to reference a  example, like what's been done with the comparison shapes? something like [this](http://bl.ocks.org/palewire/d2906de347a160f38bc0b7ca57721328) or [that](https://miro.medium.com/max/4800/0*rH8uoRRqfV87o0oM.png)?

Would it be appropriate to reference a time series graph as an example instead, like [so](https://www.aptech.com/wp-content/uploads/2016/04/g16_ts_tutorial_1.png)?

**Comment by pssachdeva** [comment]
I am just going to remove that sentence. It feels a little out of place in what is supposed to be a theory-driven, more general introduction. I'll replace it with something more general.
