### ISSUE TITLE
wishlist: accessibility resources?

### ISSUE THREAD

**Issue by e-belfer** [dlab-berkeley/R-Data-Visualization#25]
Around the intro to viridis, or else just in the resources section, it'd be really wonderful to include some reference or resources to accessible design principles (e.g. text size, color/contrast, alternative text for figures) would be amazing! If this is of interest, I'd be happy to pull a couple resources or write a sentence or two into the existing instructor script.

**Comment by asteves** [comment]
@e-belfer yes please make a PR.
