### ISSUE TITLE
column name change

### ISSUE THREAD

**Issue by meiqingli** [dlab-berkeley/R-Data-Visualization#30]
In _R-Data-Visualization-Solutions.Rmd_ , the 'age' column name of _heart.csv_  might need to be updated. Otherwise encounter errors running the code.

**Comment by asteves** [comment]
Can you say a bit more about what the error is?

**Comment by meiqingli** [comment]
> Can you say a bit more about what the error is?

When I ran the code, it returns error with 'age' not found. I suspect it is because of the wrong column name which was 'i..age' in the dataframe.

**Comment by asteves** [comment]
I do not produce this error when I run the solution code. Can you show what code you ran and any session info so I can figure out why we are seeing different results?

**Comment by meiqingli** [comment]
Here's what I got. So basically all code cells after this produce the same errors. 

`library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> # treat sex as a factor instad of continuous variable for plotting
> heart <- heart %>%
+   mutate(sex  = as.factor(sex))
> 
> B <- ggplot(heart, aes(x = sex, y = chol, fill = sex)) + 
+   geom_boxplot() +
+   scale_x_discrete(labels = c("Female", "Male")) +      # change x labels
+   scale_fill_discrete(name = "Biological Sex",          # change fill legend labels
+                       labels = c("Female", "Male")) +
+   labs(x = element_blank(),
+        y = "Serum cholestoral in mg/dl",
+        title = "Boxplot of Serum Cholesteral (mg/dl)",
+        subtitle = "by Biological Sex") +
+   theme_bw()
> 
> print(B)
> C <- ggplot(heart, aes(x = age, y = chol, 
+                        color = as.factor(sex), 
+                        shape = as.factor(sex))) +
+   geom_point(alpha = 0.7) +
+   geom_smooth(method = "lm", se = TRUE, lwd = 1) +
+   labs(x = "Age",
+        y = "Serum cholestoral in mg/dl",
+        title = "Serum Cholesteral (mg/dl) by Biological Sex") +
+   theme_bw() 
> 
> print(C)
Error in FUN(X[[i]], ...) : object 'age' not found`

**Comment by asteves** [comment]
Hmm. Again I do not produce that error when I run the Solutions file on my machine. 

How are you reading in the heart file? The fact that the names are different on your machine will produce the errors you see because the `age` column does not exist. Since nothing in the code you posted is reading in the data file, it will not change the names of columns. 

On my machine 

```
library(here)
library(ggplot2)
heart <- read.csv(here::here("data/heart.csv"))
names(heart)
```

will produce 
<img width="623" alt="Screen Shot 2022-09-19 at 11 21 20 AM" src="https://user-images.githubusercontent.com/24926205/191087040-f2fe99b0-dade-408e-8c82-78feb67a2e13.png">

Minor point. It's helpful to put code in the code blocks because otherwise Github's Markdown parser will make it look strange.

**Comment by meiqingli** [comment]
hmmmm I'm using the exactly same code as yours but not sure it reads the
column name incorrectly...

[image: image.png]

**Comment by asteves** [comment]
That image didn't load. Can you reupload?

**Comment by meiqingli** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/35152977/191100451-07e03c30-1b41-4654-9752-cc9a1f94c9df.jpg)
Here is the screenshot.

**Comment by asteves** [comment]
The error does not appear on Datahub, which leads me to believe that this has something to do with your OS. 

Can you upload the session info?

**Comment by meiqingli** [comment]
Looks like the issue was resolved after I reinstalled R and everything. But now I have a new error running the last cell: 
![Screenshot_1](https://user-images.githubusercontent.com/35152977/191108623-e228e188-22d0-4dce-8200-1069a0d91746.jpg)

**Comment by asteves** [comment]
I'm closing this issue then. Please make a new issue with the last point and your session issue so we can track appropriately
