### ISSUE TITLE
Add introduction that mimics Python-Data-Visualization

### ISSUE THREAD

**Issue by pattyf** [dlab-berkeley/R-Data-Visualization#4]
It would be great to add a 15 minute intro to data viz slide deck to this workshop. See the intro chapters in this book: https://clauswilke.com/

**Comment by pssachdeva** [comment]
We should mimic the Python Data Visualization introduction. It motivates the theory of visualization well. Furthermore, it's well suited to the Rmd format, and will standardize the concepts across both lessons.
